---
apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-cluster
  namespace: default
subsets:
  - addresses:
      - ip: 192.168.100.1
    ports:
      - port: 1
        protocol: TCP
  - addresses:
      - ip: 192.168.100.128
    ports:
      - port: 1
        protocol: TCP
  - addresses:
      - ip: 192.168.100.129
    ports:
      - port: 1
        protocol: TCP
  - addresses:
      - ip: 192.168.100.130
    ports:
      - port: 1
        protocol: TCP
  - addresses:
      - ip: 192.168.100.131
    ports:
      - port: 1
        protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-cluster
  namespace: kube-system
subsets:
  - addresses:
      - ip: 192.168.100.1
    ports:
      - port: 1
        protocol: TCP
  - addresses:
      - ip: 192.168.100.128
    ports:
      - port: 1
        protocol: TCP
  - addresses:
      - ip: 192.168.100.129
    ports:
      - port: 1
        protocol: TCP
  - addresses:
      - ip: 192.168.100.130
    ports:
      - port: 1
        protocol: TCP
  - addresses:
      - ip: 192.168.100.131
    ports:
      - port: 1
        protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: glusterfs-cluster
spec:
  ports:
    - port: 1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gluster-volume-1
spec:
  capacity:
    storage: 4Gi
  persistentVolumeReclaimPolicy: Delete
  storageClassName: storage
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  glusterfs:
    endpoints: glusterfs-cluster
    path: volume-1
    readOnly: false
